name: lattice-fits

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scipy
  - jupyter
  - tables
  - tabulate
  - black
  - pip:
    - emcee
    - gvar
    - lsqfit
    - fire
